### ISSUE TITLE
[FEATURE REQUEST] Add ability to check heartbeat?

### ISSUE THREAD

**Issue by jimmy-ho** [hibiken/asynq#155]
I would like to call into either the *asynq.Client or *asynq.Server for whether they are healthy - ie. can connect to redis etc.

It seems at the moment this is not possible, I want this so my health-check route can come back with a valid response if they are not well.

Hopefully not something hard to add, or if you can enlighten me how to get this status (if available). Thanks!

Maybe a quick:

```
healthy := true

_, err := r.redisClient.Ping().Result()
if err != nil {
	return false
}

return healthy
```

**Comment by hibiken** [comment]
@jimmy-ho Thanks for opening this issue!

This is a good feature request. It's something we can (and probably should) add to `asynq.Server`.

For context:
Current implementation has a "heartbeater" goroutine that periodically writes server state to redis (so that we can inspect it with `asynq servers` and `asynq workers` CLI commands).
And I think we can leverage that goroutine to check whether the server can talk to redis and expose an API to surface that heath check result.

Let me look into this a bit more and try to come up with a proposal. In the meantime, if you or anyone have suggestions on how the API should look, feel free to suggest in this thread. Thanks!

**Comment by hibiken** [comment]
### Initial Proposal

Add `HealthCheckFunc` in `Config`:

```go
type Config struct {
     // HealthCheckFunc is called periodically with any error encountered during ping to connected redis server.
     HealthCheckFunc func(error) {}

     // HealthCheckInterval specifies the interval between healthchecks.
     // By default the interval is 5 seconds.
     HealthCheckInterval time.Duration
}
```

By integrating with monitoring and alert system (e.g. Prometheus),  users can monitor asynq.Server's health and alert if the server is having issues.

**Comment by hibiken** [comment]
@a5r0n thanks for the comment, I think that makes sense. `Client` can expose the health of the backend resource (Redis in our case). I've been meaning to revisit how we do health checks of Redis (Redis is a critical backend for both `Client` and `Server` instances and we should expose a API to check the health). Please feel free to open a new issue 👍

**Comment by bojanz** [comment]
@hibiken Is https://github.com/hibiken/asynq/pull/585 enough, or should I go ahead and create a separate issue as well?
