### ISSUE TITLE
[PERF] High CPU consumption when load testing

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#198]
I tried to do load testing and CPU for worker (above 100%), redis and clients were above 60%

https://www.dropbox.com/s/o38apit2ulb44cp/Screen%20Shot%202020-09-18%20at%2018.07.29.png?dl=0

```go
// client.go
func main() {
	r := asynq.RedisClientOpt{Addr: "localhost:6379"}
	client := asynq.NewClient(r)
	start := time.Now()
	for i := 0; i < 1000000; i++ {
		// Create a task with typename and payload.
		t1 := asynq.NewTask("email:welcome", map[string]interface{}{"user_id": i})

		// Process the task immediately.
		_, err := client.Enqueue(t1)
		if err != nil {
			log.Fatal(err)
		}
	}
	fmt.Println(fmt.Sprintf("%s", time.Since(start)))
}
```

```go
// workers.go
func main() {
	r := asynq.RedisClientOpt{Addr: "localhost:6379"}
	srv := asynq.NewServer(r, asynq.Config{
		Concurrency: 10,
		Logger: nil,
	})

	mux := asynq.NewServeMux()
	mux.HandleFunc(WelcomeEmail, HandleWelcomeEmailTask)
	mux.HandleFunc(ReminderEmail, HandleReminderEmailTask)
	if err := srv.Run(mux); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by hibiken** [comment]
Thank you for opening this issue. 

CPU usage above 100% was most likely due to the worker process using more than one core on the machine.
With this simulated load, your Redis server is being slammed by many requests. Using redis cluster instead to balance the load across multiple instances may help.

I will look into a way to minimize the CPU usage by the package.
