### ISSUE TITLE
[FEATURE REQUEST] Is it possible to trigger a callback when status of a task is changed?

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#203]
Is it possible to trigger a function whenever status of a task is changed?

For e.g. trigger a function when task A changed it's status from `PENDING` to `ACTIVE`

Similar stuff for queue and workers:
If queue and/or workers are idle for specific time period, stop or kill such queue and/or workers to restore the resources

For e.g.

```go
type TaskMessage struct {
        ...
	Status string

	OnNew       func(i interface{}) error
	OnPending   func(i interface{}) error
	OnPause   func(i interface{}) error
	OnResume   func(i interface{}) error
	OnActive    func(i interface{}) error
	OnRetry     func(i interface{}) error
	OnScheduled func(i interface{}) error
	OnComplete  func(i interface{}) error
	OnKill      func(i interface{}) error
	OnDead      func(i interface{}) error
}
```
Is there something I could do?

**Comment by hibiken** [comment]
Thanks for opening this issue.

It's an interesting feature request, but with the current implementation this change will most likely degrade the performance significantly (e.g. we would need to deserialize the task message whenever there's a status change). I'm hesitant to make this change at this moment, but you can fork the repo and take a look at the `internal/rdb` package where task messages are managed in redis.
I will keep this issue open to see if this is a popular feature request. 

As for the second question:
> If queue and/or workers are idle for specific time period, stop or kill such queue and/or workers to restore the resources

That's why we have `Timeout` and `Deadline` option. You can read about it in [this wiki page](https://github.com/hibiken/asynq/wiki/Task-Timeout-and-Cancelation).

**Comment by itsursujit** [comment]
@hibiken Thanks for the response. I wonder those options are for Task and not Workers or Queues.

**Comment by hibiken** [comment]
Yes, the timeout and deadline are specific to each task. A worker has limited time to process a task, if the worker cannot complete its task within the timeout (or before the deadline), the task will be retried later and the worker is abandoned to reclaim resources. 

I'm not quite sure what you mean by 
>  I wonder those options are for Task and not Workers or Queues.
Could you explain this in more detail?

**Comment by hibiken** [comment]
Currently I'm not intending to support this feature. I'll close this issue for now.
