### ISSUE TITLE
[QUESTION] Is it possible to move a job from one queue to another?

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#220]
Is it possible to move a job from one queue to another queue?

Use-Case:
Sometime user has to be moved from low priority to high priority queue.

**Comment by hibiken** [comment]
Hi @sujit-baniya! Thank you for the question.

The move operation you described above is not supported currently. Once a task is put into a queue, it's stuck with that queue. This is mostly due to the fact that we use the queue name string for the hash tag for redis cluster.

A workaround would be to delete the task from the source queue and enqueue a new task to the destination queue to do a "move" operation (one downside is that this operation won't be an atomic one)

I'll close this issue since I don't see supporting this feature
