### ISSUE TITLE
[QUESTION] Is it possible to restart servers or workers when shutdown or killed or exited due to some error?

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#227]
It's possible that when servers or workers doing their work, it's possible that they are down unintentionally (Killed or Exited). 
Can we automatically start such servers or workers and start consuming from where it left?

**Comment by hibiken** [comment]
If a process gets killed forcefully (e.g. `kill -9`), the tasks will be processed again (i.e. retried) when you restart the process. 
That's why your `Handler.ProcessTask` need to be **idempotent`** because Asynq server will retry any failed tasks. 
It's your Handler's job to skip some operations if you want logic such that it'll resume from where it left off.
