### ISSUE TITLE
[FEATURE REQUEST] Can I return TaskID when calling asynq.NewTask ?

### ISSUE THREAD

**Issue by gopkg-dev** [hibiken/asynq#259]
Because the task is consumed soon after I am in Enqueue.
I want to save the taskid to the database before joining the queue.
Since Enqueue will only return after the call, it may be consumed before the taskid is saved to the database.

My English is not good, I hope you can understand what I mean.

**Comment by hibiken** [comment]
Thank you for opening this issue!

It's not difficult to make this change, but since it changes the behavior (i.e. breaking change) I want to understand the context in more detail. 

Could you elaborate the issue in more detail? 
Also, as a workaround, if you want the task not to be processed immediately after enqueue, can you use `ProcessIn` option to delay the processing?

Example:
```go
res, err := client.Enqueue(task, asynq.ProcessIn(1 * time.Minute))
```

**Comment by gopkg-dev** [comment]
Obviously this is not a good solution.
I need to monitor and manage the status of a task in my database.
But I can only get the taskid after'client.Enqueue' and save it.

It's like this now
`asynq.NewTask -> client.Enqueue -> save taskid to db -> ProcessTask -> asynq.GetTaskID -> update taskid status to db`

I hope it is like this
`asynq.NewTask -> save taskid to db -> client.Enqueue -> ProcessTask -> asynq.GetTaskID -> update taskid status to db`

**Comment by hibiken** [comment]
I see. Actually I'm currently working on a feature to track task status but it'll only be available in the future release.

In the meantime, I have another suggestion which I think is a reasonable workaround.
Instead of relying on ID generated by `asynq` package, you could generate a unique ID for each task and store it as part of the task's payload.

Example using [`uuid`](https://pkg.go.dev/github.com/google/uuid) package:
```go
id := uuid.NewString()
task := asynq.NewTask("mytask", map[string]interface{}{"task_id": id})

// Save ID to your application database.

// Enqueue task
```

Also, I'll consider making task ID available after calling `NewTask` in the future release  👍

**Comment by gopkg-dev** [comment]
Thanks for your reply, thanks 👍

**Comment by zijiwork** [comment]
`Enqueue`  Whether to support passing custom task id
