### ISSUE TITLE
[FEATURE REQUEST] Scheduler reboot cannot reschedule old tasks

### ISSUE THREAD

**Issue by bibilins** [hibiken/asynq#308]
I want to know, if the server/scheduler roboot, will the tasks that were previously enqueued but not executed be rescheduled？

**Comment by bibilins** [comment]
I had tested, enqueued a task into  scheduler, then reboot the scheduler, but it seems that scheduler was not scheduled the previous task

**Comment by JeremyCraven** [comment]
I am also curious about persistence of registered tasks with the scheduler.

**Comment by crossworth** [comment]
Hello guys, I will try to explain how the scheduler works, but I may be wrong on some aspects, so maybe we should wait to see what @hibiken says.

We use [`github.com/robfig/cron` to handle the cron part](https://github.com/hibiken/asynq/blob/95c90a5cb822877a9465cd3203235a262359096f/scheduler.go#L28), when we register a task using `Register(cronspec string, task *Task, opts ...Option) (entryID string, err error)`, we create a new [enqueueJob](https://github.com/hibiken/asynq/blob/95c90a5cb822877a9465cd3203235a262359096f/scheduler.go#L107), that has a `Run` method to be called by `robfig/cron` according to the cronspec definition. The [`enqueueJob.Run`](https://github.com/hibiken/asynq/blob/95c90a5cb822877a9465cd3203235a262359096f/scheduler.go#L119) method enqueues the task on the "normal" task handling workflow.

So if you register a cron task to be executed in 2 hours from now, starts the process and than stop the process in a few minutes, no task should be present on the task queue, since the process that enqueues the task has not been executed.

I hope that this explanation make sense.


> 
> 
> I am also curious about persistence of registered tasks with the scheduler.
> 
> My use case is scheduling a task to run on a schedule for each user only after the user performs a specific action for the first time. Currently as far as I'm aware, the only way to support this use case is determining all the users eligible for registering tasks and registering them with the scheduler before starting the scheduler. Would appreciate any guidance.

I dont think you need to register the task before starting the scheduler, the `Register` call internally calls `AddJob` and the documentation says that [you can add jobs after the scheduler has been started](https://pkg.go.dev/github.com/robfig/cron?utm_source=godoc#hdr-Usage), but there is a [map write](https://github.com/hibiken/asynq/blob/95c90a5cb822877a9465cd3203235a262359096f/scheduler.go#L157) without a lock, so it maybe panic with `concurrent write panic`. Make sure you have the task handler registered, since you cannot dynamic  register task handlers.

On your use case, on scheduler startup you could loop all the users checking if they are allowed to perform the action and if so register the task, during runtime (new user register and the scheduler is already running) you could dynamic call register, I think this should work.

**Comment by hibiken** [comment]
Thank you @bibilins for opening this issue!
@crossworth's explanation is correct. Current implementation is quite basic and it simply store all registered tasks and their cronspec in the process's memory (i.e doesn't persist it anyware), so it doesn't survive process restart.

**What we want is a fault tolerant distributed cron system**, I'll do some research and try to come up with a design and  implementation.

Also, @JeremyCraven's use case is quite interesting. Maybe we should support dynamic registering of tasks after scheduler is launched. As @crossworth mentioned, we have to make sure to use mutex to guard that `idmap`. Feel free to open a PR if anyone's interested in contributing. 

Thank you everyone for the feedback. This is a great opportunity to look into a more robust implementation of scheduler!

**Comment by duyhungtnn** [comment]
@bibilins I was facing some issues like you. I am not sure it was your case, but want to share with you and hope it could help.

When I enqueue the task with the option `time_out` or `dead_line`. After I updated the server | worker and reboot them, the system ends up with no more running tasks. It hangs forever.

## I solved by following that guide 
- https://github.com/hibiken/asynq/wiki/Task-Timeout-and-Cancelation#task-context-in-handler

### Task Context in Handler

Now that we've created tasks with the Timeout and Deadline option, we have to respect that value by reading the Done channel in the context.

The first argument passed to the Handler is context. Context. You should write your Handler in such a way that it abandons the work if the cancelation signal is received from the context.
```
func myHandler(ctx context.Context, task *asynq.Task) error {
    c := make(chan error, 1)
    go func() {
        c <- doWork(task)
    }()
    select {
    case <-ctx.Done():
        // cancelation signal received, abandon this work.
        return ctx.Err()
    case res := <-c:
        return res
    }   
}

```

**Comment by JeremyCraven** [comment]
Thanks @hibiken! We can work around registered tasks not surviving process restart.

I'll plan on following along and if the opportunity presents itself also help where possible. Thanks again!

**Comment by JeremyCraven** [comment]
> Thank you @bibilins for opening this issue!
> @crossworth's explanation is correct. Current implementation is quite basic and it simply store all registered tasks and their cronspec in the process's memory (i.e doesn't persist it anyware), so it doesn't survive process restart.
> 
> **What we want is a fault tolerant distributed cron system**, I'll do some research and try to come up with a design and implementation.
> 
> Also, @JeremyCraven's use case is quite interesting. Maybe we should support dynamic registering of tasks after scheduler is launched. As @crossworth mentioned, we have to make sure to use mutex to guard that `idmap`. Feel free to open a PR if anyone's interested in contributing.
> 
> Thank you everyone for the feedback. This is a great opportunity to look into a more robust implementation of scheduler!

Hey @hibiken. Following up, it turned out that dynamic registering of tasks ended up being a blocker for us. I took a look at the scheduler code and it wasn't obvious how to implement that. If you have any suggestions, I could take an attempt at it, but either way just following up to express interest in this feature.

**Comment by hibiken** [comment]
@JeremyCraven thank you for the update! I can revisit this and make the change within the next few days!

**Comment by hibiken** [comment]
@JeremyCraven Please update the package to v0.18.4. I made a change so that you can call `Scheduler.Register` (and also `Unregister`) concurrently. Let me know if you encounter any issues!

**Comment by JeremyCraven** [comment]
@hibiken Thank you so much! So far looks like we are unblocked.

**Comment by gf3** [comment]
@hibiken @crossworth i also have a use-case for a persisted/distributed schedule:

our platform allows shop owners to have multiple locations where goods are sold, each location has its own fulfillment time and rules. every order on our platform is associated with a location and has a fulfillment date in the future. therefore each location requires a daily job at a specific time to mark current orders as paid and then move tomorrow's orders into the "ready" state. of course we would like this schedule to persist across deploys and failures and we'd like to ensure the schedule works in a multi-node system, too.

![Store_Location_Order@2x](https://user-images.githubusercontent.com/18397/136492315-9e04a22d-93bc-4cc8-b66b-7549d1ebf0f4.png)

**Comment by hibiken** [comment]
Check out `PeriodicTaskManager` type, which was added in v0.21. 
You can store your periodic task configuration in a durable storage (e.g. file, database, etc) and write an implementation of `PeriodicTaskConfigProvider` which exports that configuration. This also supports dynamically adding/removing periodic tasks.

See [this wiki page](https://github.com/hibiken/asynq/wiki/Dynamic-Periodic-Task) for an example.

This is a new feature, so any feedback is appreciated!
