### ISSUE TITLE
[BUG] GetTaskInfo doesn't return expected errors

### ISSUE THREAD

**Issue by jonnyguio** [hibiken/asynq#340]
**Describe the bug**
The method `GetTaskInfo` of the `Inspector` doesn't return the expected error: it creates a new error appending the two possible errors to the string `asynq: `. 

**To Reproduce**
```
i := asynq.NewInspector(asynq.RedisClientOpt{Addr: "127.0.0.1:6379"})
t, err := i.GetTaskInfo("default", "non existent id")
fmt.Println(err == asynq.ErrTaskNotFound) // false
```

**Expected behavior**
```
i := asynq.NewInspector(asynq.RedisClientOpt{Addr: "127.0.0.1:6379"})
t, err := i.GetTaskInfo("default", "non existent id")
fmt.Println(err == asynq.ErrTaskNotFound) // true
```

**Screenshots**

**Environment (please complete the following information):**
 - OS: any
 - v0.18.6

**Additional context**
The documentation states:
```
GetTaskInfo retrieves task information given a task id and queue name.

Returns ErrQueueNotFound if a queue with the given name doesn't exist. Returns ErrTaskNotFound if a task with the given id doesn't exist in the queue. 
```

I believe that returning a new error, even if it can be helpful to know that the context of the error was from `asynq`, it's misleading from the actual implementation and makes handling of an expected scenario not as good as straight comparisson between errors.

**Comment by hibiken** [comment]
@jonnyguio Thank you for opening an issue!
I believe this is a documentation bug, Inspector is returning an error that wraps those sentinel error values (to allow for flexibility in adding more context in the error in the future if needed).

So instead of directly comparing to the error value, the user of the package needs to unwrap it:

```go
if errors.Is(err, asynq.ErrTaskNotFound) {
     // handle error
}
```

This pattern was taken from this blog: https://go.dev/blog/go1.13-errors

Thanks again for spotting this, I'll update the godoc 👍

**Comment by jonnyguio** [comment]
Oh, that's great! That makes a lot of sense, I missed this way of handling it.

Keep it up with the good work! :smile:
