### ISSUE TITLE
[QUESTION] Production ready ?

### ISSUE THREAD

**Issue by thejosk** [hibiken/asynq#385]
Hi @hibiken,

First of all, thanks for this amazing library, excellent job.

We plan to use this library for background job processing for a new project in our company (>10 years in the industry). I know you've mentioned in https://github.com/hibiken/asynq#stability-and-compatibility that there could be breaking changes until a major version is released, I'm wondering if anything has changed and how breaking could this changes be?, What would you suggest ?

Thanks again.

**Comment by hibiken** [comment]
Hi @thejosk, thank you for posting this question!

I believe that README needs an update, since the library is quite stable at this point.
Breaking changes are rare at this point, and if we need to make such changes, we document thoroughly in the release notes and CHANGLOG. So as long as you use go.mod to specify the version number for asynq, it's unlikely to break your application. 

Also, if we make changes in the schema we use to store tasks and metadata in redis, we provide the `migrate` command via the CLI to upgrade to a new version (but I don't foresee any such change coming in the future at this point). 

Please let me know if you have more concerns or follow up questions 👍

**Comment by thejosk** [comment]
Awesome, thank you. Closing this for now.
