### ISSUE TITLE
Is it necessary for the `LREM` argument count = 0 ?

### ISSUE THREAD

**Issue by ryan961** [hibiken/asynq#389]
> `LREM`:  Removes the first count occurrences of elements equal to element from the list stored at key
....
> count = 0: Remove all elements equal to element.

In the case of a certain amount of data, it will cause a lot of slow queries, which will cause Redis CPU to explode, and this will enter a vicious cycle that can't be handled.
https://github.com/hibiken/asynq/blob/dff2e3a33639338c648599bf6ea83f835feec4bf/internal/rdb/rdb.go#L312
https://github.com/hibiken/asynq/blob/dff2e3a33639338c648599bf6ea83f835feec4bf/internal/rdb/rdb.go#L344
...

**Comment by hibiken** [comment]
@ryalu Thank you for reporting this issue!

These `LREM` operations are executed against the `asynq:{qname}:active` list which can only grow up to the number specified by `Config.Concurrency` so should be bounded to smallish number (e.g. ~100 or so).

But you made a good point, that this count may only need to be set to 1 since we only need to remove just one element from the list during normal operation. I didn't put too much thoughts there but I wanted to guarantee that we remove the id from the list. We can run benchmark tests with different concurrency settings, and see if changing this to 1 would make it more performant.
