### ISSUE TITLE
[FEATURE REQUEST] Distributed Scheduler

### ISSUE THREAD

**Issue by aakashbajaj** [hibiken/asynq#395]
**Is your feature request related to a problem? Please describe.**
RIght now, a dedicated scheduler needs to be running. If that instance/service goes down, there's no way of recovery (specifically in kubernetes pod)

**Describe the solution you'd like**
Multiple schedulers register themselves on redis and maintain a master copy of Scheduler Entries. So, that if one instance goes down, other can pick right back up from there.

**Comment by hibiken** [comment]
@aakashbajaj Thank you for opening an issue!

Can you run a multiple instances of `PeriodicTaskManager` ([see wiki here for more details](https://github.com/hibiken/asynq/wiki/Dynamic-Periodic-Task)) and store the periodic task configuration in a durable storage (e.g. Database, file in a distrubted filesystem, etc) and source that with `PeriodicTaskConfigProvider`?

To prevent these multiple instances of `PeriodicTaskManager`s from enqueueing duplicate tasks, you should be able to use the combinations of the following task options.
- `TaskID(uniqueID)`
- `Retention(duration)`
(This is kind of a workaround since the current `Unique` option doesn't work well if the task gets processed quickly, see the discussion below for details).

This was previously discussed here in [this discussion](https://github.com/hibiken/asynq/discussions/376).

Let me know if you have more questions or feedback!

**Comment by aakashbajaj** [comment]
Thanks @hibiken for the suggestion. I'll look into this.

**Comment by hibiken** [comment]
@aakashbajaj Closing this for now, but feel free to open this with a follow-up question or feedback 👍
