### ISSUE TITLE
ERROR: Failed to extend lease for tasks

### ISSUE THREAD

**Issue by lvsoso** [hibiken/asynq#401]
```shell

asynq: pid=6499 2022/02/20 05:20:00.136535 ERROR: Failed to extend lease for tasks [11a5aed1-ec41-4e63-9c14-91b834bac2e1]: ERR syntax error


```

https://github.com/hibiken/asynq/blob/cabf8d36273ced35d2df62cde4001b43ab7748bd/internal/rdb/rdb.go#L944

Redis version >= 6.2.0: Added the `GT` and `LT` options.

I encounter the error when using the redis  that it's version low than 6.2.0.

**Comment by hibiken** [comment]
@lvsoso Thank you for creating this issue!

I missed the supported redis version when I was browsing the zadd documentation. Since `GT` is not strictly needed (although it'd be nice if we can add it to convey the intention to "extend" the lease), I'll remove that option for now. XX option should be sufficient in our case, since we check the expired lease before sending the ZADD command to redis.
