### ISSUE TITLE
[QUESTION] Get results or waiting until the task is done?

### ISSUE THREAD

**Issue by lucy9x** [hibiken/asynq#511]
I'm testing with asynq, doesn't the current version support waiting until the task is done?

Eg :

```go
info, err := client.Enqueue(task)
var result string
info.Get(&string)
```

With `info.Get(&string)` will wait main thread until async task is completed

**Comment by hibiken** [comment]
@lucy9x Thank you for creating an issue. 
It's not quite what you described above, but we do offer looking up task's status via its ID. You can retrieve task info by calling [`Inspector.GetTaskInfo`](https://pkg.go.dev/github.com/hibiken/asynq#Inspector.GetTaskInfo). You need to handle polling yourself. And make sure to set the `Retention` option so that successfully processed task sticks around to get the status and the result (otherwise, the task will be deleted as soon as it's processed successfully)
